version: '3'

services:
  postgres-databse-container-tasks:
    image: postgres:alpine
    ports:
      - "5438:5432"
    container_name: "postgres-databse-container-tasks"
    restart: always
    volumes:
      - ./database-postgres-tasks:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASS}"

volumes:
  postgres-databse-container-tasks: