@baseUrl = https://nodedeploytask-api.onrender.com/api

POST  {{baseUrl}}/register
content-type: application/json

{
   "name": "Diógenes Ribeiro de Oliveira",
   "email": "io.riboliveira@gmail.com", 
   "password": "S@@laada390390", 
   "confirm_password": "S@@laada390390" 
}

###

POST {{baseUrl}}/user/sign-up
content-type: application/json

{
	"email": "diogenes.riboliveira@gmail.com",
	"password": "S@@alada390390"
}

###
POST {{baseUrl}}/create/task
Content-Type: application/json

{
   "title": "Titulo de teste",
   "description": "Descrição para teste",
   "difficulty": 6,
   "status": false,
   "authorId": 1,
   "endsDate": "2023-10-21"
}

###

GET {{baseUrl}}/all/tasks

###

DELETE {{baseUrl}}/delete/task/7