@baseUrl = http://localhost:8080/api

POST  {{baseUrl}}/register
content-type: application/json

{
   "name": "Usuário de teste",
   "email": "user.test@gmail.com", 
   "password": "senhaDeTeste", 
   "confirm_password": "senhaDeTeste" 
}

###

POST {{baseUrl}}/create/task
Content-Type: application/json

{
   "title": "Titulo de teste",
   "description": "Descrição para teste",
   "difficulty": 6,
   "status": false,
   "authorId": 1,
}